name: hive_test
description: Initialize a temporary Hive database for testing
version: 1.0.0
repository: https://github.com/netsells/hive_test

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.4
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.5.1
  very_good_analysis: ^2.0.3

import_sorter:
  emojis: true
