name: hive_ce_test
description: Initialize a temporary Hive database for testing
version: 2.0.0
repository: https://github.com/chandrabezzo/hive_ce_test

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  hive_ce: ^2.13.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
