name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install project dependencies
        run: dart pub get

      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Run static analysis
        run: dart analyze .

      - name: Run tests
        run: dart test --coverage test/

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
